campaign = 'UL17'

[path]
input_samples = '../output/UL17/processed_samples/'
input = '../output/UL17/'
output = '../output/UL17/'

[validation_binning]
bins = [
    {"eta" = [0.0, 1.3], "pT" = [30, 40, 50, 80, 100, 120, 250, 1000]},
    {"eta" = [1.3, 2.5], "pT" = [30, 40, 50, 80, 100, 120, 250, 1000]},
    {"eta" = [2.5, 3.0], "pT" = [30, 40, 50, 80, 100, 120, 250, 1000]},
]

[SF_binning]
bins = [
    {"eta" = [0.0, 1.3], "pT" = [30, 80, 8000]},
    {"eta" = [1.3, 2.5], "pT" = [30, 8000]},
    {"eta" = [2.5, 3.0], "pT" = [30, 8000]},
]

[qgl_WP]
loose = 0.07
medium = 0.54
tight = 0.90

[deepjet_WP]
loose = 0.12
medium = 0.27
tight = 0.48

[particlenet_WP]
loose = 0.16
medium = 0.32
tight = 0.54

[WP_binning]
bins = [
     {"eta" = [0.0, 1.3], "pT" = [30, 35, 40, 45, 50, 60, 70, 85, 105, 130, 175, 230, 8000]},
     {"eta" = [1.3, 2.5], "pT" = [30, 35, 40, 45, 50, 60, 70, 85, 105, 130, 175, 8000]},
]
